language: python
sudo: false
services:
- docker
python:
- '3.6'

cache:
  directories:
  - "$HOME/.cache/pip"
before_script:
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && \
    chmod +x kubectl && sudo mv kubectl /usr/local/bin/
