--- 
matrix: 
  include: 
    - 
      before_install: 
        - "GO111MODULE=on go get sigs.k8s.io/kind"
        - "kind create cluster"
        - "export KUBECONFIG=\"$(kind get kubeconfig-path --name=\"kind\")\""
        - "curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        - "chmod +x ./kubectl"
        - "./kubectl get nodes -o wide"
        - "./kubectl get pods --all-namespaces -o wide"
        - "./kubectl get services --all-namespaces -o wide"
      go: 
        - "1.13"
      install: true
      language: go
      services: 
        - docker
      sudo: false
    - 
      install: true
      python: 
        - "3.6"
      script: 
        - "echo \"Run your tests here\""
      services: 
        - docker
        - xvfb
      sudo: false
